// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhokhktzvzmvxhldspzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFob2toa3R6dnptdnhobGRzcHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjA4NjIsImV4cCI6MjA3MDQzNjg2Mn0.4fu-1IVAVrzc4e3Nt4REjeWYDl4bhwoCUrjOq1EumUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});